version: '3.9'
services:
  carService:
    container_name: carService
    image: node:15.5.0-alpine3.12
    depends_on:
      - rabbitmq
    command: sh -c "npm i && npm start"
    env_file:
      - ./car-service/.env
    working_dir: /app
    volumes:
      - ./car-service:/app
    links:
      - rabbitmq
    networks:
      - trg_test
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq

  penaltyService:
    container_name: penaltyService
    image: node:15.5.0-alpine3.12
    depends_on:
      - rabbitmq
      - mongo
    command: sh -c "npm i && npm start"
    env_file:
      - ./penalty-service/.env
    working_dir: /app
    volumes:
      - ./penalty-service:/app
    links:
      - rabbitmq
      - mongo
    networks:
      - trg_test
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
      - MONGO_URL=mongodb://root:example@localhost:27017/trg?authSource=admin

  apiService:
    container_name: apiService
    image: node:15.5.0-alpine3.12
    depends_on:
      - mongo
    command: sh -c "npm i && npm start"
    env_file:
      - ./api-service/.env
    working_dir: /app
    volumes:
      - ./api-service:/app
    links:
      - mongo
    networks:
      - trg_test
    environment:
      - MONGO_URL=mongodb://root:example@localhost:27017/trg?authSource=admin
    ports:
    - 3000:3000

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - trg_test

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: trg
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./database:/data/db
    ports:
      - '27017:27017'
    networks:
      - trg_test

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - trg_test

networks:
  trg_test:
    driver: bridge
